// The seed catalog (spec §4.5) — the full layered SYNTHETIC opportunity set for the pilot cells.
// SYNTHETIC ONLY; no live/real people. Deterministic (a static value; ids are stable literals).
//
// Three pilot cells (cellKeys in the planner's `cabin/subtopic|mode` format), reused verbatim by the
// plan fixtures (`plans.ts`) so catalog ⇄ plan match by string equality:
//   • CELL_AUDIO = "music-sound/audio-systems|build"  — the RICH cell: every MentorSourceLayer
//     (AI/FAMILY/NEAR_PEER/THIN_EXPERT/MASTER) + every AudienceChannel
//     (COMPETITION/PUBLISHING/COMMUNITY/MARKETPLACE), plus the pending/rejected/stage-gate spread.
//   • CELL_GAMEDEV = "code-computers/game-dev|build"   — the S1 cell: two WARM mentors, an
//     age-gated WARM teen mentor, an S4-only MASTER (stage-gate proof), one audience opening.
//   • CELL_CHESS = "games-strategy/chess|perform"      — the plurality cell: an independent spike.
//
// Coverage baked in for the engine's gates/ranking:
//   - vetting: `mn-pending-tech` (pending) + `au-rejected-community` (rejected) MUST be filtered.
//   - stage:   `gd-master`/`mn-master` (minStage S4) hidden from S1/earlier plans; `au-community-early`
//              (REAL_COMMUNITY but minStage S4) isolates the stage gate from the level filter.
//   - age:     `gd-ai-warm-teen` (ageTier 12-14) hidden from a 6-8 kid though role/stage/rep all fit.
import type { Opportunity } from "../model.js";

export const CELL_AUDIO = "music-sound/audio-systems|build";
export const CELL_GAMEDEV = "code-computers/game-dev|build";
export const CELL_CHESS = "games-strategy/chess|perform";

// ── CELL_AUDIO — the rich cell (every mentor layer + every audience channel) ──────────────────────
const AUDIO_MENTORS: readonly Opportunity[] = [
  {
    id: "mn-ai-warm",
    kind: "mentor",
    title: "AI practice coach — audio systems warm-up",
    cellKey: CELL_AUDIO,
    modes: ["build", "investigate"],
    fillsRole: "WARM",
    sourceLayer: "AI",
    minStage: "S1_IGNITION",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.72,
  },
  {
    id: "mn-fam-warm",
    kind: "mentor",
    title: "Family friend who builds PA rigs (warm door-opener)",
    cellKey: CELL_AUDIO,
    modes: ["build", "collaborate"],
    fillsRole: "WARM",
    sourceLayer: "FAMILY",
    minStage: "S1_IGNITION",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.65,
  },
  {
    id: "mn-peer-tech",
    kind: "mentor",
    title: "Near-peer apprentice — crossover & enclosure builds",
    cellKey: CELL_AUDIO,
    modes: ["build", "debug"],
    fillsRole: "TECHNICAL",
    sourceLayer: "NEAR_PEER",
    minStage: "S2_FOUNDATIONS",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.7,
  },
  {
    id: "mn-pending-tech",
    kind: "mentor",
    title: "Unvetted technical reviewer (awaiting vetting)",
    cellKey: CELL_AUDIO,
    modes: ["build"],
    fillsRole: "TECHNICAL",
    sourceLayer: "NEAR_PEER",
    minStage: "S2_FOUNDATIONS",
    ageTier: "9-11",
    vetting: "pending",
    reputation: 0.9,
  },
  {
    id: "mn-thin-expert",
    kind: "mentor",
    title: "Thin-slice domain expert — DIY loudspeaker design review",
    cellKey: CELL_AUDIO,
    modes: ["build", "investigate"],
    fillsRole: "DOMAIN_EXPERT",
    sourceLayer: "THIN_EXPERT",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.85,
  },
  {
    id: "mn-master",
    kind: "mentor",
    title: "Master acoustician — signature mentorship",
    cellKey: CELL_AUDIO,
    modes: ["build", "compose"],
    fillsRole: "MASTER",
    sourceLayer: "MASTER",
    minStage: "S4_SIGNATURE",
    ageTier: "12-14",
    vetting: "vetted",
    reputation: 0.95,
  },
];

const AUDIO_AUDIENCES: readonly Opportunity[] = [
  {
    id: "au-peers-community",
    kind: "audience",
    title: "Builders' club show-and-tell (mentor peers)",
    cellKey: CELL_AUDIO,
    modes: ["build", "explain"],
    level: "MENTOR_PEERS",
    channel: "COMMUNITY",
    minStage: "S2_FOUNDATIONS",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.6,
  },
  {
    id: "au-community-showcase",
    kind: "audience",
    title: "Local maker-fair audio showcase (real community)",
    cellKey: CELL_AUDIO,
    modes: ["build", "perform"],
    level: "REAL_COMMUNITY",
    channel: "COMMUNITY",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.75,
  },
  {
    id: "au-competition",
    kind: "audience",
    title: "Junior audio-build competition (deadline)",
    cellKey: CELL_AUDIO,
    modes: ["build"],
    level: "REAL_COMMUNITY",
    channel: "COMPETITION",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.8,
    availability: { deadline: "2026-09-01" },
  },
  {
    id: "au-community-early",
    kind: "audience",
    title: "Invitational community night (signature-only)",
    cellKey: CELL_AUDIO,
    modes: ["build", "perform"],
    level: "REAL_COMMUNITY",
    channel: "COMMUNITY",
    minStage: "S4_SIGNATURE",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.99,
  },
  {
    id: "au-rejected-community",
    kind: "audience",
    title: "Rejected community listing (failed vetting)",
    cellKey: CELL_AUDIO,
    modes: ["build"],
    level: "REAL_COMMUNITY",
    channel: "COMMUNITY",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "rejected",
    reputation: 0.95,
  },
  {
    id: "au-publishing-field",
    kind: "audience",
    title: "Audio-engineering journal build feature (field)",
    cellKey: CELL_AUDIO,
    modes: ["build", "explain"],
    level: "FIELD",
    channel: "PUBLISHING",
    minStage: "S4_SIGNATURE",
    ageTier: "12-14",
    vetting: "vetted",
    reputation: 0.9,
  },
  {
    id: "au-marketplace-field",
    kind: "audience",
    title: "Boutique-speaker marketplace listing (field)",
    cellKey: CELL_AUDIO,
    modes: ["build"],
    level: "FIELD",
    channel: "MARKETPLACE",
    minStage: "S4_SIGNATURE",
    ageTier: "12-14",
    vetting: "vetted",
    reputation: 0.7,
    availability: { slots: 3 },
  },
];

// ── CELL_GAMEDEV — the S1 cell (warm mentors + age/stage-gate proofs) ─────────────────────────────
const GAMEDEV: readonly Opportunity[] = [
  {
    id: "gd-ai-warm",
    kind: "mentor",
    title: "AI game-dev buddy (warm start)",
    cellKey: CELL_GAMEDEV,
    modes: ["build", "debug"],
    fillsRole: "WARM",
    sourceLayer: "AI",
    minStage: "S1_IGNITION",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.7,
  },
  {
    id: "gd-fam-warm",
    kind: "mentor",
    title: "Cousin who ships small games (family door-opener)",
    cellKey: CELL_GAMEDEV,
    modes: ["build", "collaborate"],
    fillsRole: "WARM",
    sourceLayer: "FAMILY",
    minStage: "S1_IGNITION",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.6,
  },
  {
    id: "gd-ai-warm-teen",
    kind: "mentor",
    title: "Teen-tier AI mentor (age-gated to 12-14)",
    cellKey: CELL_GAMEDEV,
    modes: ["build"],
    fillsRole: "WARM",
    sourceLayer: "AI",
    minStage: "S1_IGNITION",
    ageTier: "12-14",
    vetting: "vetted",
    reputation: 0.99,
  },
  {
    id: "gd-master",
    kind: "mentor",
    title: "Master game designer (signature-only)",
    cellKey: CELL_GAMEDEV,
    modes: ["build"],
    fillsRole: "MASTER",
    sourceLayer: "MASTER",
    minStage: "S4_SIGNATURE",
    ageTier: "12-14",
    vetting: "vetted",
    reputation: 0.95,
  },
  {
    id: "gd-community",
    kind: "audience",
    title: "Indie game jam showcase (real community)",
    cellKey: CELL_GAMEDEV,
    modes: ["build", "perform"],
    level: "REAL_COMMUNITY",
    channel: "COMMUNITY",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.7,
  },
];

// ── CELL_CHESS — the plurality cell (an independent spike) ─────────────────────────────────────────
const CHESS: readonly Opportunity[] = [
  {
    id: "ch-ai-warm",
    kind: "mentor",
    title: "AI chess coach (warm)",
    cellKey: CELL_CHESS,
    modes: ["perform", "investigate"],
    fillsRole: "WARM",
    sourceLayer: "AI",
    minStage: "S1_IGNITION",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.6,
  },
  {
    id: "ch-thin-expert",
    kind: "mentor",
    title: "Club-master reviewer — annotated games (domain expert)",
    cellKey: CELL_CHESS,
    modes: ["perform"],
    fillsRole: "DOMAIN_EXPERT",
    sourceLayer: "THIN_EXPERT",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.82,
  },
  {
    id: "ch-community",
    kind: "audience",
    title: "Scholastic club ladder night (mentor peers)",
    cellKey: CELL_CHESS,
    modes: ["perform"],
    level: "MENTOR_PEERS",
    channel: "COMMUNITY",
    minStage: "S2_FOUNDATIONS",
    ageTier: "6-8",
    vetting: "vetted",
    reputation: 0.55,
  },
  {
    id: "ch-competition",
    kind: "audience",
    title: "Regional scholastic tournament (deadline)",
    cellKey: CELL_CHESS,
    modes: ["perform"],
    level: "REAL_COMMUNITY",
    channel: "COMPETITION",
    minStage: "S3_AUTHORSHIP",
    ageTier: "9-11",
    vetting: "vetted",
    reputation: 0.78,
    availability: { deadline: "2026-08-15" },
  },
];

/** The full seed catalog — a flat, deterministic list across all pilot cells. */
export const SEED_CATALOG: readonly Opportunity[] = [
  ...AUDIO_MENTORS,
  ...AUDIO_AUDIENCES,
  ...GAMEDEV,
  ...CHESS,
];
