// GENERATED by scripts/gen-palette.mjs — do not edit by hand.
// 8 fills at OKLCH L=0.72 C=0.08000, hues [25,60,110,150,200,255,300,340].
export const STROKE = "#002a3a";
export const HIGHLIGHT = "#fcf4ef";
export const STROKE_WIDTH = 9;
export const FILLS = ["#d2918b","#ca9971","#a7a96e","#80b38a","#63b4b8","#83a7d6","#ac9ad0","#c791b4"] as const;
export const ALLOWED_FILLS: ReadonlySet<string> = new Set([...FILLS, "#ffffff", HIGHLIGHT]);
