// GENERATED by scripts/gen-palette.mjs — do not edit by hand.
// 8 fills at OKLCH L=0.72 C=0.13, hues [25,60,110,150,200,255,300,340].
export const STROKE = "#002a3a";
export const HIGHLIGHT = "#fcf4ef";
export const STROKE_WIDTH = 9;
export const FILLS = ["#eb827b","#df8f48","#aaab3f","#62bb78","#00bcc5","#6aa7f4","#b191ea","#da83be"] as const;
export const ALLOWED_FILLS: ReadonlySet<string> = new Set([...FILLS, "#ffffff", HIGHLIGHT]);
