import {
  ASSET_KEYS,
  type AgeBand,
  type ArenaView,
  type AssetKeyRegistry,
  type AvatarAnimationSpec,
  type AvatarAnimationState,
  type AvatarState,
  BASE_LAYOUT,
  BIOMES,
  type BasePlacement,
  type BiomeIdentity,
  CAMERA3D,
  CATALOG,
  type CameraConfig3D,
  type CelebrationEvent,
  type CohortBase,
  type CompetencyNode,
  type CooperativeMissionResult,
  type Cosmetic,
  type CosmeticEligibility,
  type CosmeticRule,
  type DeviceCaps,
  EASINGS,
  FIXTURE,
  LAMBDAS,
  LIGHTING,
  type LightingConfig,
  MOTION,
  type MotionSpec,
  type MotionToken,
  type NearPeerStanding,
  type NodeMasterySignal,
  type NodePosition,
  type NodeState,
  type NodeTransform3D,
  PALETTE,
  PARALLAX3D,
  POSTFX,
  type Palette,
  type ParallaxLayer,
  type PostFxConfig,
  type Presentation,
  type ProgressionState,
  QUALITY_TIERS,
  type QualityBudget,
  type QualityTier,
  type QuestWorld,
  type RewardRepresentation,
  SECTIONS,
  SOUND_CUES,
  type Section,
  type SoundCue,
  TIERS,
  TYPOGRAPHY,
  type Tier,
  type VisualBand,
  WATER,
  WORLD_SCALE,
  type WaterConfig,
  type WorldLayout,
  type WorldTheme,
  type WorldTransform3D,
} from "@gt100k/arena-world";
import { describe, expect, expectTypeOf, it } from "vitest";

type CompletedP0Types = [
  AgeBand,
  ArenaView,
  AssetKeyRegistry,
  AvatarAnimationSpec,
  AvatarAnimationState,
  AvatarState,
  BasePlacement,
  BiomeIdentity,
  CameraConfig3D,
  CelebrationEvent,
  CohortBase,
  CompetencyNode,
  CooperativeMissionResult,
  Cosmetic,
  CosmeticEligibility,
  CosmeticRule,
  DeviceCaps,
  LightingConfig,
  MotionSpec,
  MotionToken,
  NearPeerStanding,
  NodeMasterySignal,
  NodePosition,
  NodeState,
  NodeTransform3D,
  Palette,
  ParallaxLayer,
  PostFxConfig,
  Presentation,
  ProgressionState,
  QualityBudget,
  QualityTier,
  QuestWorld,
  RewardRepresentation,
  Section,
  SoundCue,
  Tier,
  VisualBand,
  WaterConfig,
  WorldLayout,
  WorldTheme,
  WorldTransform3D,
];

describe("arena-world package entrypoint", () => {
  it("exports every completed P0 runtime value through the package name", () => {
    expect([
      ASSET_KEYS,
      BASE_LAYOUT,
      BIOMES,
      CAMERA3D,
      CATALOG,
      EASINGS,
      FIXTURE,
      LAMBDAS,
      LIGHTING,
      MOTION,
      PALETTE,
      PARALLAX3D,
      POSTFX,
      QUALITY_TIERS,
      SECTIONS,
      SOUND_CUES,
      TIERS,
      TYPOGRAPHY,
      WATER,
      WORLD_SCALE,
    ]).not.toContain(undefined);
  });

  it("exports every completed P0 domain type through the package name", () => {
    expectTypeOf<CompletedP0Types>().toBeArray();
  });
});
