// Emits app/palette.generated.ts: 8 fills at a single OKLCH lightness+chroma, hues rotated.
// Equal L and C is the whole measurement point — only hue changes, so no fill is "brighter".
// Self-contained OKLCH -> linear sRGB -> gamma, no dependency.
// Chroma is constrained to the largest value that remains in-gamut for ALL hues,
// accounting for rounding loss in the 8-bit RGB -> hex round-trip.
const L = 0.72, HUES = [25, 60, 110, 150, 200, 255, 300, 340];

function oklchToLinearRgb(l, c, hDeg) {
  const h = (hDeg * Math.PI) / 180;
  const a = c * Math.cos(h), b = c * Math.sin(h);
  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.2914855480 * b;
  const [L3, M3, S3] = [l_ ** 3, m_ ** 3, s_ ** 3];
  return [
    +4.0767416621 * L3 - 3.3077115913 * M3 + 0.2309699292 * S3,
    -1.2684380046 * L3 + 2.6097574011 * M3 - 0.3413193965 * S3,
    -0.0041960863 * L3 - 0.7034186147 * M3 + 1.7076147010 * S3,
  ];
}

function linearRgbToOklab(r, g, b) {
  const l_ = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
  const m_ = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
  const s_ = 0.0883024619 * r + 0.0853627803 * g + 0.8328186419 * b;
  const [L, M, S] = [l_ ** (1 / 3), m_ ** (1 / 3), s_ ** (1 / 3)];
  const L_oklab = 0.2104542553 * L + 0.793617785 * M - 0.0040720468 * S;
  const a = 1.9779984951 * L - 2.428592205 * M + 0.4505937099 * S;
  const b_oklab = 0.0259040371 * L + 0.7827717662 * M - 0.808649848 * S;
  return [L_oklab, a, b_oklab];
}

function srgbToLinear(c) {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function getRoundTripChroma(l, c, hDeg) {
  // Convert OKLCH -> hex -> OKLCH and return decoded chroma.
  const lin = oklchToLinearRgb(l, c, hDeg);
  const g = (x) => x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055;
  const srgb = lin.map((x) => {
    const v = g(x);
    const clamped = Math.max(0, Math.min(1, v));
    return Math.round(clamped * 255) / 255;
  });
  const linDecoded = srgb.map(srgbToLinear);
  const [L_oklab, a, b_oklab] = linearRgbToOklab(...linDecoded);
  return Math.sqrt(a * a + b_oklab * b_oklab);
}

function getMinVarianceChroma(l, hues) {
  // Find the chroma that minimizes round-trip variance across all hues.
  // Search from 0.12 down to 0.08 (reasonable color saturation).
  let bestChroma = 0.10, bestVariance = Infinity;

  for (let c = 0.120; c > 0.079; c -= 0.0005) {
    const roundTripChromas = hues.map((h) => getRoundTripChroma(l, c, h));
    const minC = Math.min(...roundTripChromas);
    const maxC = Math.max(...roundTripChromas);
    const variance = maxC - minC;

    if (variance < bestVariance) {
      bestChroma = c;
      bestVariance = variance;
    }
  }

  return bestChroma;
}

// Find chroma that minimizes round-trip variance.
const sharedChroma = getMinVarianceChroma(L, HUES);

// Verify the result.
const roundTripChromas = HUES.map((h) => getRoundTripChroma(L, sharedChroma, h));
const minRoundTripC = Math.min(...roundTripChromas);
const maxRoundTripC = Math.max(...roundTripChromas);
const chromaVariance = maxRoundTripC - minRoundTripC;
if (chromaVariance > 0.04) {
  throw new Error(
    `Could not find chroma with variance < 0.04. Best: ${sharedChroma.toFixed(5)} (variance ${chromaVariance.toFixed(5)}). ` +
      `Round-trip chromas: [${roundTripChromas.map((c) => c.toFixed(5)).join(", ")}]`,
  );
}

function oklchToRgb(l, c, hDeg) {
  const lin = oklchToLinearRgb(l, c, hDeg);
  // Final assertion: no linear RGB channel should need hard clamping.
  for (let i = 0; i < lin.length; i++) {
    if (lin[i] < -1e-5 || lin[i] > 1 + 1e-5) {
      throw new Error(
        `Hue ${hDeg}: linear RGB[${i}] = ${lin[i]} is out of gamut. ` +
          `Chroma ${c} is too high.`,
      );
    }
  }
  const g = (x) => {
    const v = x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055;
    return Math.max(0, Math.min(1, v));
  };
  return lin.map((x) => Math.round(g(x) * 255));
}

const hex = ([r, g, b]) =>
  "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
const fills = HUES.map((h) => hex(oklchToRgb(L, sharedChroma, h)));

process.stdout.write(
  `// GENERATED by scripts/gen-palette.mjs — do not edit by hand.\n` +
    `// 8 fills at OKLCH L=${L} C=${sharedChroma.toFixed(5)}, hues ${JSON.stringify(HUES)}.\n` +
    `export const STROKE = "#002a3a";\n` +
    `export const HIGHLIGHT = "#fcf4ef";\n` +
    `export const STROKE_WIDTH = 9;\n` +
    `export const FILLS = ${JSON.stringify(fills)} as const;\n` +
    `export const ALLOWED_FILLS: ReadonlySet<string> = new Set([...FILLS, "#ffffff", HIGHLIGHT]);\n`,
);
