// Emits app/palette.generated.ts: 8 fills at a single OKLCH lightness+chroma, hues rotated.
// Equal L and C is the whole measurement point — only hue changes, so no fill is "brighter".
// Self-contained OKLCH -> linear sRGB -> gamma, no dependency.
const L = 0.72, C = 0.13, HUES = [25, 60, 110, 150, 200, 255, 300, 340];

function oklchToRgb(l, c, hDeg) {
  const h = (hDeg * Math.PI) / 180;
  const a = c * Math.cos(h), b = c * Math.sin(h);
  const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = l - 0.0894841775 * a - 1.2914855480 * b;
  const [L3, M3, S3] = [l_ ** 3, m_ ** 3, s_ ** 3];
  const lin = [
    +4.0767416621 * L3 - 3.3077115913 * M3 + 0.2309699292 * S3,
    -1.2684380046 * L3 + 2.6097574011 * M3 - 0.3413193965 * S3,
    -0.0041960863 * L3 - 0.7034186147 * M3 + 1.7076147010 * S3,
  ];
  const g = (x) => {
    const v = x <= 0.0031308 ? 12.92 * x : 1.055 * Math.pow(x, 1 / 2.4) - 0.055;
    return Math.max(0, Math.min(1, v));
  };
  return lin.map((x) => Math.round(g(x) * 255));
}
const hex = ([r, g, b]) =>
  "#" + [r, g, b].map((v) => v.toString(16).padStart(2, "0")).join("");
const fills = HUES.map((h) => hex(oklchToRgb(L, C, h)));

process.stdout.write(
  `// GENERATED by scripts/gen-palette.mjs — do not edit by hand.\n` +
    `// 8 fills at OKLCH L=${L} C=${C}, hues ${JSON.stringify(HUES)}.\n` +
    `export const STROKE = "#002a3a";\n` +
    `export const HIGHLIGHT = "#fcf4ef";\n` +
    `export const STROKE_WIDTH = 9;\n` +
    `export const FILLS = ${JSON.stringify(fills)} as const;\n` +
    `export const ALLOWED_FILLS: ReadonlySet<string> = new Set([...FILLS, "#ffffff", HIGHLIGHT]);\n`,
);
