import type { ActivityEvent } from "./activity";

export const ACTIVITY_GOLDEN_V1: ActivityEvent[] = [
  {
    zoneId: "music",
    probeId: "m_build",
    domain: "sound_music",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "music",
    probeId: "m_perform",
    domain: "sound_music",
    workMode: "perform",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "code",
    probeId: "c_build",
    domain: "symbols_math",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "art",
    probeId: "a_build",
    domain: "visual_design",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "music",
    probeId: "m_build",
    domain: "sound_music",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "music",
    probeId: "m_perform",
    domain: "sound_music",
    workMode: "perform",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "music",
    probeId: "m_debug",
    domain: "sound_music",
    workMode: "debug",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "code",
    probeId: "c_build",
    domain: "symbols_math",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 7,
    intervention: { source: "reminder" },
  },
  {
    zoneId: "music",
    probeId: "m_build",
    domain: "sound_music",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 30,
  },
];

export const ACTIVITY_GOLDEN_WORKMODE_V1: ActivityEvent[] = [
  {
    zoneId: "music",
    probeId: "m_build",
    domain: "sound_music",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "code",
    probeId: "c_build",
    domain: "symbols_math",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "art",
    probeId: "a_build",
    domain: "visual_design",
    workMode: "build",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "music",
    probeId: "m_perform",
    domain: "sound_music",
    workMode: "perform",
    action: "open",
    kind: "explore",
    dayOffset: 0,
  },
  {
    zoneId: "music",
    probeId: "m_build",
    domain: "sound_music",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "code",
    probeId: "c_build",
    domain: "symbols_math",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "art",
    probeId: "a_build",
    domain: "visual_design",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 7,
  },
  {
    zoneId: "code",
    probeId: "c_build",
    domain: "symbols_math",
    workMode: "build",
    action: "open",
    kind: "return",
    dayOffset: 30,
  },
];

export const ACTIVITY_GOLDEN_INSUFFICIENT_V1: ActivityEvent[] = ACTIVITY_GOLDEN_V1.slice(0, 4);
