// The curated library: the shelf a child actually opens.
//
// Under a launcher this file IS the product's content. A child taps a subtopic and sees what is
// filed under it here, so an empty subtopic is a dead end they walk into and a dead URL is the same
// thing arriving later. `validateLibrary` enforces the first; `scripts/check-links.ts` is how you
// catch the second before a child does.
//
// HOW THESE WERE CHOSEN
//
// Every URL was fetched and its status recorded. Anything that could not be opened was excluded
// rather than guessed at, including one otherwise-excellent Science Buddies activity that sits
// behind a Cloudflare challenge no automated check can clear: unverifiable is treated the same as
// unavailable, because the cost of being wrong is a child landing on nothing.
//
// Sources are biased hard toward institutions — public broadcasters, universities, museums, national
// agencies, long-running nonprofits — over individual creators. That is a durability judgement, not
// a snobbery one. Pew Research Center, "When Online Content Disappears" (2024, ~1M pages sampled
// from Common Crawl): 38% of pages that existed in 2013 were gone within a decade, and about one in
// five pages from 2021 were gone within two years.
// <https://www.pewresearch.org/data-labs/2024/05/17/when-online-content-disappears/>
// A library of personal blogs and one-off videos would be a fifth dead before the children using it
// finished primary school.
//
// `affordedModes` describes what THE CHILD DOES, not what the resource is. A video explaining how
// synths work is `investigate`; a build-a-synth walkthrough is `build`. This is the only place the
// mode axis enters a launcher, since picking a subtopic says nothing about how a child wants to
// work — so getting it right here is what keeps the second axis alive at all.
//
// `ageTiers` is strict. A resource is tagged 6-8 only if a six-year-old could actually use it, not
// if the topic is nominally suitable. A tier tagged optimistically is a dead end wearing a label.
//
// SYNTHETIC-FREE, but not child-tested. These are real public resources. Nothing here has been in
// front of a real child, and G3/G4 still gate that.
import type { CuratedResource } from "./model.js";

/** The shipped curated library. Ordered by domain path, then id, so diffs stay readable. */
export const SEED_LIBRARY: readonly CuratedResource[] = [
  {
    id: "res-art-motion-3d-modeling-blender-5-2-lts-manual",
    title: "Blender 5.2 LTS Manual",
    url: "https://docs.blender.org/manual/en/latest/",
    domainPath: ["art-motion", "3d-modeling"],
    affordedModes: ["build", "debug"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-3d-modeling-blender-youtube",
    title: "Blender — YouTube",
    url: "https://www.youtube.com/@BlenderOfficial",
    domainPath: ["art-motion", "3d-modeling"],
    affordedModes: ["investigate", "build"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-3d-modeling-freecad-your-own-3d-parametric-modeler",
    title: "FreeCAD: Your own 3D parametric modeler",
    url: "https://www.freecad.org/",
    domainPath: ["art-motion", "3d-modeling"],
    affordedModes: ["build"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-3d-modeling-training-blender-studio",
    title: "Training — Blender Studio",
    url: "https://studio.blender.org/training/",
    domainPath: ["art-motion", "3d-modeling"],
    affordedModes: ["build"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-3d-modeling-tutorials-blender",
    title: "Tutorials — Blender",
    url: "https://www.blender.org/support/tutorials/",
    domainPath: ["art-motion", "3d-modeling"],
    affordedModes: ["build", "compose"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-animation-acmi-school-programs-and-resources",
    title: "ACMI School Programs and Resources",
    url: "https://www.acmi.net.au/education/school-program-and-resources/",
    domainPath: ["art-motion", "animation"],
    affordedModes: ["investigate", "compose"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-animation-animation-nfb",
    title: "Animation — NFB",
    url: "https://www.nfb.ca/animation/",
    domainPath: ["art-motion", "animation"],
    affordedModes: ["investigate"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-animation-nfb-education-national-film-board-of-canada",
    title: "NFB Education — National Film Board of Canada",
    url: "https://www.nfb.ca/education/",
    domainPath: ["art-motion", "animation"],
    affordedModes: ["investigate", "compose"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-animation-opentoonz",
    title: "OpenToonz",
    url: "https://opentoonz.github.io/e/",
    domainPath: ["art-motion", "animation"],
    affordedModes: ["compose"],
    reputation: 0.65,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-animation-the-wick-editor",
    title: "The Wick Editor",
    url: "https://www.wickeditor.com/",
    domainPath: ["art-motion", "animation"],
    affordedModes: ["compose", "build"],
    reputation: 0.6,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-video-editing-filmmaking-into-film",
    title: "Filmmaking — Into Film",
    url: "https://www.intofilm.org/films-and-resources/filmmaking",
    domainPath: ["art-motion", "video-editing"],
    affordedModes: ["compose", "collaborate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-video-editing-kdenlive-26-04-manual",
    title: "Kdenlive 26.04 Manual",
    url: "https://docs.kdenlive.org/en/",
    domainPath: ["art-motion", "video-editing"],
    affordedModes: ["compose", "debug"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-video-editing-shotcut-tutorial-videos",
    title: "Shotcut — Tutorial Videos",
    url: "https://shotcut.org/tutorials/",
    domainPath: ["art-motion", "video-editing"],
    affordedModes: ["compose", "debug"],
    reputation: 0.7,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-visual-kids-and-families-education-at-the-getty",
    title: "Kids and Families (Education at the Getty)",
    url: "https://www.getty.edu/education/kids_families/",
    domainPath: ["art-motion", "visual"],
    affordedModes: ["compose", "investigate"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-visual-krita-digital-painting-creative-freedom",
    title: "Krita — Digital Painting. Creative Freedom.",
    url: "https://www.krita.org/en/",
    domainPath: ["art-motion", "visual"],
    affordedModes: ["compose"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-visual-street-art-google-arts-culture",
    title: "Street Art — Google Arts & Culture",
    url: "https://artsandculture.google.com/project/street-art",
    domainPath: ["art-motion", "visual"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-art-motion-visual-tate-kids-youtube",
    title: "Tate Kids — YouTube",
    url: "https://www.youtube.com/@TateKids",
    domainPath: ["art-motion", "visual"],
    affordedModes: ["investigate", "compose"],
    reputation: 0.9,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-agentic-engineering-code-org-ai-curriculum",
    title: "Code.org – AI curriculum",
    url: "https://code.org/ai",
    domainPath: ["code-computers", "agentic-engineering"],
    affordedModes: ["investigate", "build"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-agentic-engineering-day-of-ai-mit-raise",
    title: "Day of AI (MIT RAISE)",
    url: "https://dayofai.org/",
    domainPath: ["code-computers", "agentic-engineering"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-agentic-engineering-machine-learning-for-kids",
    title: "Machine Learning for Kids",
    url: "https://machinelearningforkids.co.uk/",
    domainPath: ["code-computers", "agentic-engineering"],
    affordedModes: ["build"],
    reputation: 0.7,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-agentic-engineering-teachable-machine",
    title: "Teachable Machine",
    url: "https://teachablemachine.withgoogle.com/",
    domainPath: ["code-computers", "agentic-engineering"],
    affordedModes: ["build", "investigate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-game-dev-code-org-game-lab",
    title: "Code.org Game Lab",
    url: "https://code.org/educate/gamelab",
    domainPath: ["code-computers", "game-dev"],
    affordedModes: ["build", "debug"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-game-dev-godot-docs-step-by-step",
    title: "Godot Docs – Step by step",
    url: "https://docs.godotengine.org/en/stable/getting_started/step_by_step/index.html",
    domainPath: ["code-computers", "game-dev"],
    affordedModes: ["build", "debug"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-game-dev-invent-your-own-computer-games-with-python",
    title: "Invent Your Own Computer Games with Python",
    url: "https://inventwithpython.com/invent4thed/",
    domainPath: ["code-computers", "game-dev"],
    affordedModes: ["build"],
    reputation: 0.65,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-game-dev-microsoft-makecode-arcade",
    title: "Microsoft MakeCode Arcade",
    url: "https://arcade.makecode.com/",
    domainPath: ["code-computers", "game-dev"],
    affordedModes: ["build"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-game-dev-scratch-imagine-program-share",
    title: "Scratch – Imagine, Program, Share",
    url: "https://scratch.mit.edu/",
    domainPath: ["code-computers", "game-dev"],
    affordedModes: ["build", "compose", "collaborate"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-hardware-arduino-documentation",
    title: "Arduino Documentation",
    url: "https://docs.arduino.cc/",
    domainPath: ["code-computers", "hardware"],
    affordedModes: ["build", "debug"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-hardware-cs-unplugged",
    title: "CS Unplugged",
    url: "https://www.csunplugged.org/en/",
    domainPath: ["code-computers", "hardware"],
    affordedModes: ["investigate", "collaborate"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-hardware-make-it-code-it-micro-bit-foundation",
    title: "Make it: code it (micro:bit Foundation)",
    url: "https://microbit.org/projects/make-it-code-it/",
    domainPath: ["code-computers", "hardware"],
    affordedModes: ["build"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-hardware-nand-to-tetris",
    title: "Nand to Tetris",
    url: "https://www.nand2tetris.org/",
    domainPath: ["code-computers", "hardware"],
    affordedModes: ["build", "investigate"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-python-computer-science-circles-university-of-water",
    title: "Computer Science Circles (University of Waterloo CEMC)",
    url: "https://cscircles.cemc.uwaterloo.ca/",
    domainPath: ["code-computers", "python"],
    affordedModes: ["build", "debug"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-python-futurecoder",
    title: "futurecoder",
    url: "https://futurecoder.io/",
    domainPath: ["code-computers", "python"],
    affordedModes: ["build", "debug"],
    reputation: 0.55,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-python-raspberry-pi-foundation-projects",
    title: "Raspberry Pi Foundation – Projects",
    url: "https://projects.raspberrypi.org/en/pathways/python-intro",
    domainPath: ["code-computers", "python"],
    affordedModes: ["build"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-python-the-python-tutorial-python-org",
    title: "The Python Tutorial (python.org)",
    url: "https://docs.python.org/3/tutorial/",
    domainPath: ["code-computers", "python"],
    affordedModes: ["build", "investigate"],
    reputation: 0.9,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-code-computers-python-welcome-to-pygame-zero",
    title: "Welcome to Pygame Zero",
    url: "https://pygame-zero.readthedocs.io/en/stable/",
    domainPath: ["code-computers", "python"],
    affordedModes: ["build"],
    reputation: 0.7,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-board-games-american-go-association",
    title: "American Go Association",
    url: "https://www.usgo.org/",
    domainPath: ["games-strategy", "board-games"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-board-games-learn-to-play-go-online-go-server",
    title: "Learn to play Go (Online Go Server)",
    url: "https://online-go.com/learn-to-play-go",
    domainPath: ["games-strategy", "board-games"],
    affordedModes: ["perform"],
    reputation: 0.55,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-board-games-nim-7-nrich",
    title: "Nim-7 (NRICH)",
    url: "https://nrich.maths.org/problems/nim-7",
    domainPath: ["games-strategy", "board-games"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.9,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-board-games-royal-game-of-ur-information-and-rules-the-g",
    title: "Royal Game of Ur: Information and Rules (The Getty)",
    url: "https://www.getty.edu/education/college/ancient_rome_at_home/pdf/ur_game.pdf",
    domainPath: ["games-strategy", "board-games"],
    affordedModes: ["build", "perform"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-board-games-solving-together-got-it-nrich",
    title: "Solving Together – Got It! (NRICH)",
    url: "https://nrich.maths.org/solving-together-got-it",
    domainPath: ["games-strategy", "board-games"],
    affordedModes: ["investigate", "collaborate"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-chess-chess-basics-practice-lichess",
    title: "Chess Basics / Practice (Lichess)",
    url: "https://lichess.org/practice",
    domainPath: ["games-strategy", "chess"],
    affordedModes: ["perform", "debug"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-chess-how-to-play-chess-7-rules-to-get-you-started",
    title: "How to Play Chess: 7 Rules To Get You Started (Chess.com)",
    url: "https://www.chess.com/learn-how-to-play-chess",
    domainPath: ["games-strategy", "chess"],
    affordedModes: ["perform", "explain"],
    reputation: 0.7,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-chess-learn-chess-by-playing-lichess",
    title: "Learn chess - by playing! (Lichess)",
    url: "https://lichess.org/learn",
    domainPath: ["games-strategy", "chess"],
    affordedModes: ["perform", "investigate"],
    reputation: 0.8,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-chess-saint-louis-chess-club-youtube-channel",
    title: "Saint Louis Chess Club (YouTube channel)",
    url: "https://www.youtube.com/@STLChessClub",
    domainPath: ["games-strategy", "chess"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-poker-odds-and-evens-nrich-university-of-cambridge",
    title: "Odds and Evens (NRICH, University of Cambridge)",
    url: "https://nrich.maths.org/problems/odds-and-evens",
    domainPath: ["games-strategy", "poker"],
    affordedModes: ["investigate"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-games-strategy-poker-poker-theory-and-analytics-mit-opencoursewar",
    title: "Poker Theory and Analytics (MIT OpenCourseWare 15.S50)",
    url: "https://ocw.mit.edu/courses/15-s50-poker-theory-and-analytics-january-iap-2015/",
    domainPath: ["games-strategy", "poker"],
    affordedModes: ["investigate"],
    reputation: 0.95,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-marketing-admongo-lesson-plans-ftc",
    title: "Admongo Lesson Plans (FTC)",
    url: "https://www.consumer.ftc.gov/Admongo/lesson-plans.html",
    domainPath: ["influence-media", "marketing"],
    affordedModes: ["investigate", "build"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-marketing-co-co-s-adversmarts",
    title: "Co-Co's AdverSmarts",
    url: "https://mediasmarts.ca/digital-media-literacy/educational-games/co-cos-adversmarts",
    domainPath: ["influence-media", "marketing"],
    affordedModes: ["investigate", "build"],
    reputation: 0.85,
    ageTiers: ["6-8"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-marketing-persuasion-in-the-media-bbc-bitesize",
    title: "Persuasion in the media (BBC Bitesize)",
    url: "https://www.bbc.co.uk/bitesize/articles/z8c7dp3",
    domainPath: ["influence-media", "marketing"],
    affordedModes: ["investigate", "persuade"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-marketing-spotting-media-influence-grade-5-lesson",
    title: "Spotting Media Influence (Grade 5 lesson)",
    url: "https://www.commonsense.org/education/digital-literacy/spotting-media-influence",
    domainPath: ["influence-media", "marketing"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.92,
    ageTiers: ["9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-marketing-understanding-ads-grade-1-lesson",
    title: "Understanding Ads (Grade 1 lesson)",
    url: "https://www.commonsense.org/education/digital-literacy/understanding-ads",
    domainPath: ["influence-media", "marketing"],
    affordedModes: ["investigate"],
    reputation: 0.92,
    ageTiers: ["6-8"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-156-optical-illusions-visual-phenomena",
    title: "156 Optical Illusions / Visual Phenomena",
    url: "https://michaelbach.de/ot/",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["investigate"],
    reputation: 0.7,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-best-illusion-of-the-year-contest",
    title: "Best Illusion of the Year Contest",
    url: "https://illusionoftheyear.com/",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-neuroscience-and-psychology-frontiers-for-yo",
    title: "Neuroscience and Psychology – Frontiers for Young Minds",
    url: "https://kids.frontiersin.org/collections/neuroscience-and-psychology",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-neuroscience-for-kids",
    title: "Neuroscience For Kids",
    url: "https://faculty.washington.edu/chudler/neurok.html",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["investigate", "build"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-science-snacks-perception-exploratorium",
    title: "Science Snacks: Perception (Exploratorium)",
    url: "https://www.exploratorium.edu/snacks/subject/perception",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["build", "investigate"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-psychology-thinking-sensing-behaving-brainfacts-org",
    title: "Thinking, Sensing & Behaving (BrainFacts.org)",
    url: "https://www.brainfacts.org/thinking-sensing-and-behaving",
    domainPath: ["influence-media", "psychology"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.95,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-publishing-bbc-young-reporter",
    title: "BBC Young Reporter",
    url: "https://www.bbc.co.uk/teach/young-reporter",
    domainPath: ["influence-media", "publishing"],
    affordedModes: ["compose", "investigate"],
    reputation: 0.95,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-publishing-kid-reporters-notebook-scholastic",
    title: "Kid Reporters' Notebook (Scholastic)",
    url: "https://kpcnotebook.scholastic.com/",
    domainPath: ["influence-media", "publishing"],
    affordedModes: ["compose", "investigate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-publishing-read-gov-kids-library-of-congress",
    title: "Read.gov: Kids (Library of Congress)",
    url: "https://read.gov/kids/",
    domainPath: ["influence-media", "publishing"],
    affordedModes: ["investigate", "compose"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-publishing-stone-soup",
    title: "Stone Soup",
    url: "https://stonesoup.com/",
    domainPath: ["influence-media", "publishing"],
    affordedModes: ["compose"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-storytelling-1001-stories-the-story-museum",
    title: "1001 Stories (The Story Museum)",
    url: "https://1001stories.co.uk/",
    domainPath: ["influence-media", "storytelling"],
    affordedModes: ["investigate"],
    reputation: 0.75,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-storytelling-creative-writing-ks2-english-bbc-bitesize",
    title: "Creative writing – KS2 English (BBC Bitesize)",
    url: "https://www.bbc.co.uk/bitesize/topics/zpccwmn",
    domainPath: ["influence-media", "storytelling"],
    affordedModes: ["compose", "build"],
    reputation: 0.95,
    ageTiers: ["9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-storytelling-how-to-plan-your-story-bbc-bitesize",
    title: "How to plan your story (BBC Bitesize)",
    url: "https://www.bbc.co.uk/bitesize/articles/zqmkh39",
    domainPath: ["influence-media", "storytelling"],
    affordedModes: ["compose", "build"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-storytelling-pixar-in-a-box-the-art-of-storytelling",
    title: "Pixar in a Box: The Art of Storytelling",
    url: "https://www.khanacademy.org/computing/pixar/storytelling",
    domainPath: ["influence-media", "storytelling"],
    affordedModes: ["compose", "investigate"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-influence-media-storytelling-storyline-online",
    title: "Storyline Online",
    url: "https://storylineonline.net/",
    domainPath: ["influence-media", "storytelling"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-3d-printing-3d-resources-nasa-science",
    title: "3D Resources — NASA Science",
    url: "https://nasa3d.arc.nasa.gov/models",
    domainPath: ["making-engineering", "3d-printing"],
    affordedModes: ["build", "investigate"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-3d-printing-nih-3d",
    title: "NIH 3D",
    url: "https://3d.nih.gov/",
    domainPath: ["making-engineering", "3d-printing"],
    affordedModes: ["investigate", "build"],
    reputation: 0.9,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-3d-printing-prusa-academy",
    title: "Prusa Academy",
    url: "https://academy.prusa3d.com/",
    domainPath: ["making-engineering", "3d-printing"],
    affordedModes: ["build", "explain"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-3d-printing-prusa-knowledge-base",
    title: "Prusa Knowledge Base",
    url: "https://help.prusa3d.com/",
    domainPath: ["making-engineering", "3d-printing"],
    affordedModes: ["debug", "care"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-3d-printing-tinkercad-learn-designs",
    title: "Tinkercad — Learn: Designs",
    url: "https://www.tinkercad.com/learn/designs",
    domainPath: ["making-engineering", "3d-printing"],
    affordedModes: ["build"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-electronics-adafruit-learning-system",
    title: "Adafruit Learning System",
    url: "https://learn.adafruit.com/",
    domainPath: ["making-engineering", "electronics"],
    affordedModes: ["build", "debug"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-electronics-arduino-education",
    title: "Arduino Education",
    url: "https://www.arduino.cc/education/",
    domainPath: ["making-engineering", "electronics"],
    affordedModes: ["build", "explain"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-electronics-sparkfun-learn-tutorials",
    title: "SparkFun Learn — Tutorials",
    url: "https://learn.sparkfun.com/tutorials",
    domainPath: ["making-engineering", "electronics"],
    affordedModes: ["build", "debug"],
    reputation: 0.7,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-electronics-tinkercad-learn-circuits",
    title: "Tinkercad — Learn: Circuits",
    url: "https://www.tinkercad.com/learn/circuits",
    domainPath: ["making-engineering", "electronics"],
    affordedModes: ["build", "debug"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-robotics-first-lego-league",
    title: "FIRST LEGO League",
    url: "https://www.firstinspires.org/robotics/fll",
    domainPath: ["making-engineering", "robotics"],
    affordedModes: ["build", "collaborate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-robotics-microsoft-makecode-for-micro-bit",
    title: "Microsoft MakeCode for micro:bit",
    url: "https://makecode.microbit.org/",
    domainPath: ["making-engineering", "robotics"],
    affordedModes: ["build", "debug"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-making-engineering-robotics-raspberry-pi-foundation-projects",
    title: "Raspberry Pi Foundation — Projects",
    url: "https://projects.raspberrypi.org/en/pathways/robotics-intro",
    domainPath: ["making-engineering", "robotics"],
    affordedModes: ["build", "debug"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-competition-math-alcumus-art-of-problem-solving",
    title: "Alcumus (Art of Problem Solving)",
    url: "https://artofproblemsolving.com/alcumus",
    domainPath: ["math-puzzles", "competition-math"],
    affordedModes: ["perform", "investigate"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-competition-math-mathcounts-trainer-aops",
    title: "MATHCOUNTS Trainer (AoPS)",
    url: "https://artofproblemsolving.com/mathcounts_trainer",
    domainPath: ["math-puzzles", "competition-math"],
    affordedModes: ["perform"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-competition-math-past-amc-8-10-12-aime-problems-and-solutions",
    title: "Past AMC 8/10/12 & AIME Problems and Solutions",
    url: "https://live.poshenloh.com/past-contests",
    domainPath: ["math-puzzles", "competition-math"],
    affordedModes: ["perform", "investigate"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-competition-math-problem-of-the-week-archive-mathcounts",
    title: "Problem of the Week Archive (MATHCOUNTS)",
    url: "https://www.mathcounts.org/resources/problem-week-archive",
    domainPath: ["math-puzzles", "competition-math"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-logic-puzzles-cs-unplugged",
    title: "CS Unplugged",
    url: "https://www.csunplugged.org/en/topics/sorting-networks/",
    domainPath: ["math-puzzles", "logic-puzzles"],
    affordedModes: ["build", "collaborate"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-logic-puzzles-maths-puzzles-transum",
    title: "Maths Puzzles (Transum)",
    url: "https://www.transum.org/software/Puzzles/",
    domainPath: ["math-puzzles", "logic-puzzles"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.7,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-logic-puzzles-national-cipher-challenge-university-of-sout",
    title: "National Cipher Challenge (University of Southampton)",
    url: "https://www.cipherchallenge.org/",
    domainPath: ["math-puzzles", "logic-puzzles"],
    affordedModes: ["debug", "collaborate"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-logic-puzzles-nrich-university-of-cambridge",
    title: "NRICH (University of Cambridge)",
    url: "https://nrich.maths.org/",
    domainPath: ["math-puzzles", "logic-puzzles"],
    affordedModes: ["investigate", "collaborate"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-logic-puzzles-puzzle-calendars-mathigon",
    title: "Puzzle Calendars (Mathigon)",
    url: "https://mathigon.org/puzzles",
    domainPath: ["math-puzzles", "logic-puzzles"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-statistics-censusatschool-new-zealand",
    title: "CensusAtSchool New Zealand",
    url: "https://new.censusatschool.org.nz/",
    domainPath: ["math-puzzles", "statistics"],
    affordedModes: ["collaborate", "investigate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-statistics-data-nuggets",
    title: "Data Nuggets",
    url: "https://datanuggets.org/",
    domainPath: ["math-puzzles", "statistics"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.8,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-statistics-dollar-street-gapminder",
    title: "Dollar Street (Gapminder)",
    url: "https://www.gapminder.org/dollar-street",
    domainPath: ["math-puzzles", "statistics"],
    affordedModes: ["investigate"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-statistics-seeing-theory-brown-university",
    title: "Seeing Theory (Brown University)",
    url: "https://seeing-theory.brown.edu/",
    domainPath: ["math-puzzles", "statistics"],
    affordedModes: ["investigate"],
    reputation: 0.9,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-math-puzzles-statistics-statistics-in-schools-u-s-census-bureau",
    title: "Statistics in Schools (U.S. Census Bureau)",
    url: "https://www.census.gov/programs-surveys/sis.html",
    domainPath: ["math-puzzles", "statistics"],
    affordedModes: ["investigate", "build"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-audio-systems-chapter-17-sound-waves-the-physics-classroom",
    title: "Chapter 17: Sound Waves (The Physics Classroom)",
    url: "https://www.physicsclassroom.com/class/sound",
    domainPath: ["music-sound", "audio-systems"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-audio-systems-music-acoustics-unsw-school-of-physics",
    title: "Music Acoustics (UNSW School of Physics)",
    url: "https://newt.phys.unsw.edu.au/music/",
    domainPath: ["music-sound", "audio-systems"],
    affordedModes: ["investigate"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-audio-systems-physclips-waves-and-sound-unsw",
    title: "Physclips: Waves and Sound (UNSW)",
    url: "https://www.animations.physics.unsw.edu.au/waves-sound/",
    domainPath: ["music-sound", "audio-systems"],
    affordedModes: ["investigate"],
    reputation: 0.85,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-audio-systems-sound-ks2-science-bbc-bitesize",
    title: "Sound – KS2 Science – BBC Bitesize",
    url: "https://www.bbc.co.uk/bitesize/topics/zgffr82",
    domainPath: ["music-sound", "audio-systems"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-instruments-classics-for-kids-90-9-wguc",
    title: "Classics for Kids (90.9 WGUC)",
    url: "https://www.classicsforkids.com/",
    domainPath: ["music-sound", "instruments"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.8,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-instruments-dso-kids-dallas-symphony-orchestra",
    title: "DSO Kids (Dallas Symphony Orchestra)",
    url: "https://www.dsokids.com/",
    domainPath: ["music-sound", "instruments"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-instruments-instruments-philharmonia-orchestra",
    title: "Instruments (Philharmonia Orchestra)",
    url: "https://philharmonia.co.uk/resources/instruments/",
    domainPath: ["music-sound", "instruments"],
    affordedModes: ["investigate"],
    reputation: 0.85,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-instruments-learning-synths-ableton",
    title: "Learning Synths (Ableton)",
    url: "https://learningsynths.ableton.com/",
    domainPath: ["music-sound", "instruments"],
    affordedModes: ["build", "perform"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-instruments-sfs-kids-san-francisco-symphony",
    title: "SFS Kids (San Francisco Symphony)",
    url: "https://www.sfskids.org/",
    domainPath: ["music-sound", "instruments"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.9,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-music-theory-learning-resources-new-york-philharmonic",
    title: "Learning Resources (New York Philharmonic)",
    url: "https://www.nyphil.org/education/kidzone/",
    domainPath: ["music-sound", "music-theory"],
    affordedModes: ["compose", "investigate"],
    reputation: 0.9,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-music-theory-musictheory-net-lessons",
    title: "musictheory.net – Lessons",
    url: "https://www.musictheory.net/lessons",
    domainPath: ["music-sound", "music-theory"],
    affordedModes: ["investigate", "build"],
    reputation: 0.7,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-music-theory-open-music-theory-version-2",
    title: "Open Music Theory (Version 2)",
    url: "https://viva.pressbooks.pub/openmusictheory/",
    domainPath: ["music-sound", "music-theory"],
    affordedModes: ["investigate"],
    reputation: 0.8,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-music-theory-teoria-music-theory-web",
    title: "teoria: Music Theory Web",
    url: "https://teoria.com/",
    domainPath: ["music-sound", "music-theory"],
    affordedModes: ["investigate", "perform"],
    reputation: 0.65,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-production-audacity-manual",
    title: "Audacity Manual",
    url: "https://manual.audacityteam.org/",
    domainPath: ["music-sound", "production"],
    affordedModes: ["build", "debug"],
    reputation: 0.75,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-production-beepbox",
    title: "BeepBox",
    url: "https://www.beepbox.co/",
    domainPath: ["music-sound", "production"],
    affordedModes: ["compose"],
    reputation: 0.5,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-production-chrome-music-lab",
    title: "Chrome Music Lab",
    url: "https://musiclab.chromeexperiments.com/",
    domainPath: ["music-sound", "production"],
    affordedModes: ["compose", "build"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-music-sound-production-learning-music-ableton",
    title: "Learning Music (Ableton)",
    url: "https://learningmusic.ableton.com/",
    domainPath: ["music-sound", "production"],
    affordedModes: ["build", "compose"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-astronomy-astronomy-picture-of-the-day",
    title: "Astronomy Picture of the Day",
    url: "https://apod.nasa.gov/apod/astropix.html",
    domainPath: ["science-nature", "astronomy"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.95,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-astronomy-esa-space-for-kids",
    title: "ESA — Space for Kids",
    url: "https://www.esa.int/kids/en/home",
    domainPath: ["science-nature", "astronomy"],
    affordedModes: ["investigate"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-astronomy-eyes-on-the-solar-system-nasa-jpl",
    title: "Eyes on the Solar System — NASA/JPL",
    url: "https://eyes.nasa.gov/apps/solar-system/",
    domainPath: ["science-nature", "astronomy"],
    affordedModes: ["investigate"],
    reputation: 0.95,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-astronomy-stellarium-web-online-star-map",
    title: "Stellarium Web Online Star Map",
    url: "https://stellarium-web.org/",
    domainPath: ["science-nature", "astronomy"],
    affordedModes: ["investigate"],
    reputation: 0.75,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-astronomy-the-schools-observatory",
    title: "The Schools' Observatory",
    url: "https://www.schoolsobservatory.org/",
    domainPath: ["science-nature", "astronomy"],
    affordedModes: ["investigate", "build"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-botany-activities-kidsgardening",
    title: "Activities — KidsGardening",
    url: "https://www.kidsgardening.org/garden-activities/",
    domainPath: ["science-nature", "botany"],
    affordedModes: ["care", "build"],
    reputation: 0.7,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-botany-learn-discover-missouri-botanical-garden",
    title: "Learn & Discover — Missouri Botanical Garden",
    url: "https://www.missouribotanicalgarden.org/learn-discover.aspx",
    domainPath: ["science-nature", "botany"],
    affordedModes: ["investigate"],
    reputation: 0.9,
    ageTiers: ["9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-botany-outdoor-learning-resources-for-schools-woodl",
    title: "Outdoor Learning Resources For Schools — Woodland Trust",
    url: "https://www.woodlandtrust.org.uk/support-us/act/your-school/resources/",
    domainPath: ["science-nature", "botany"],
    affordedModes: ["investigate", "care"],
    reputation: 0.85,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-botany-plants-ks1-science-bbc-bitesize",
    title: "Plants — KS1 Science — BBC Bitesize",
    url: "https://www.bbc.co.uk/bitesize/topics/zpxnyrd",
    domainPath: ["science-nature", "botany"],
    affordedModes: ["investigate"],
    reputation: 0.95,
    ageTiers: ["6-8"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-botany-school-gardening-rhs",
    title: "School gardening / RHS",
    url: "https://schoolgardening.rhs.org.uk/",
    domainPath: ["science-nature", "botany"],
    affordedModes: ["care", "build"],
    reputation: 0.9,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-physics-fermilab-education-and-public-engagement",
    title: "Fermilab Education and Public Engagement",
    url: "https://ed.fnal.gov/",
    domainPath: ["science-nature", "physics"],
    affordedModes: ["investigate"],
    reputation: 0.9,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-physics-forces-and-motion-basics-phet-interactive-si",
    title: "Forces and Motion: Basics — PhET Interactive Simulations",
    url: "https://phet.colorado.edu/en/simulations/forces-and-motion-basics",
    domainPath: ["science-nature", "physics"],
    affordedModes: ["investigate", "build"],
    reputation: 0.95,
    ageTiers: ["6-8", "9-11", "12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-physics-ks3-science-bbc-bitesize",
    title: "KS3 Science — BBC Bitesize",
    url: "https://www.bbc.co.uk/bitesize/subjects/zng4d2p",
    domainPath: ["science-nature", "physics"],
    affordedModes: ["investigate", "explain"],
    reputation: 0.95,
    ageTiers: ["12-14"],
    provenance: "curated:seed-2026-07",
  },
  {
    id: "res-science-nature-physics-scishow-kids-youtube",
    title: "SciShow Kids — YouTube",
    url: "https://www.youtube.com/@SciShowKids",
    domainPath: ["science-nature", "physics"],
    affordedModes: ["investigate"],
    reputation: 0.7,
    ageTiers: ["6-8", "9-11"],
    provenance: "curated:seed-2026-07",
  },
];
