/**
 * How pitch is represented in this app, and how it becomes a frequency.
 *
 * ONE REPRESENTATION, CHOSEN TO MAKE A WHOLE CLASS OF BUG IMPOSSIBLE
 * ------------------------------------------------------------------------------------------------
 * Pitch is a **diatonic scale degree**: a plain integer counting steps up (or down, if negative)
 * the major scale from its tonic. Degree 0 is the tonic, 7 is the octave above it, -1 is the note a
 * step below.
 *
 * The alternative — storing semitones — was rejected for a design reason rather than a taste one.
 * `docs/superpowers/specs/2026-07-27-music-cabin-design.md` requires the wrong note in Tune Repair
 * to be **inside the key** and wrong only for the *phrase*, because "find the note outside the
 * permitted set" is set membership, which is deduction, which belongs in the `logic-games` cabin.
 * If pitches were semitones, staying in key would be a *check* somebody could forget. As degrees it
 * is structural: every integer is a legal note in the key, so an out-of-key note cannot be
 * generated by accident.
 *
 * WHY NO NUMBER FROM HERE EVER REACHES THE SCREEN
 * ------------------------------------------------------------------------------------------------
 * Rule **R1** of the cabin design: the visual channel is musical notation, never numeric. Pitch
 * renders as vertical position, duration as horizontal extent. A degree is an index into a layout,
 * not a label to print — if a degree, semitone count, interval size or note name is ever rendered as
 * part of a puzzle's solvable state, the puzzle has become arithmetic and belongs in `math`.
 */

/**
 * Semitones above the tonic for each degree of the major scale.
 *
 * Major rather than minor purely because its steps are the most familiar shape to a listener, so a
 * broken phrase reads as broken faster. Nothing else in the design depends on the choice, and a
 * second mode could be added as another table without touching a caller.
 */
export const MAJOR_STEPS = [0, 2, 4, 5, 7, 9, 11] as const;

/** How many degrees make an octave. */
export const DEGREES_PER_OCTAVE = MAJOR_STEPS.length;

/** Semitones in an octave. */
const SEMITONES_PER_OCTAVE = 12;

/**
 * Convert a diatonic degree to semitones above the tonic.
 *
 * Handles negative degrees and degrees past the octave, which is the whole reason this is a function
 * and not an array lookup: phrases wander across octave boundaries and every caller would otherwise
 * have to get the floor-division right. `Math.floor` rather than truncation matters here — for
 * degree −1 the octave is −1 and the index is 6, which truncation gets wrong.
 */
export function degreeToSemitone(degree: number): number {
  const octave = Math.floor(degree / DEGREES_PER_OCTAVE);
  const index = degree - octave * DEGREES_PER_OCTAVE;
  return octave * SEMITONES_PER_OCTAVE + MAJOR_STEPS[index]!;
}

/** Concert A, the reference every equal-tempered frequency is derived from. */
export const A4_HZ = 440;

/**
 * Equal-tempered frequency for a semitone offset from A4.
 *
 * Twelve equal divisions of the octave: each semitone multiplies frequency by the twelfth root of
 * two. Offset 0 is A4, 12 is the A above it, −12 the A below.
 */
export function frequencyForSemitone(semitonesFromA4: number, a4Hz: number = A4_HZ): number {
  return a4Hz * 2 ** (semitonesFromA4 / SEMITONES_PER_OCTAVE);
}

/**
 * Where the cabin's tonic sits, as a semitone offset from A4.
 *
 * −9 is middle C. Chosen so a phrase spanning a couple of octaves either side stays in the range
 * where pitch is easiest to hear and compare, rather than drifting into the mud at the bottom or
 * the whistle at the top.
 */
export const TONIC_FROM_A4 = -9;

/** Frequency for a diatonic degree, relative to the cabin's tonic. */
export function frequencyForDegree(degree: number, a4Hz: number = A4_HZ): number {
  return frequencyForSemitone(TONIC_FROM_A4 + degreeToSemitone(degree), a4Hz);
}
