import type { QuestWorld } from "./model";

export const FIXTURE = {
  nodes: [
    {
      id: "count-cove",
      title: "Counting",
      sections: ["math"],
      prerequisites: [],
      region: "numbers-coast",
      landmark: "Counting Lighthouse",
      transferCritical: false,
    },
    {
      id: "add-atoll",
      title: "Addition",
      sections: ["math"],
      prerequisites: ["count-cove"],
      region: "numbers-coast",
      landmark: "Abacus Jetty",
      transferCritical: false,
    },
    {
      id: "place-value-point",
      title: "Place Value",
      sections: ["math"],
      prerequisites: ["add-atoll"],
      region: "numbers-coast",
      landmark: "Tide-Pool Terraces",
      transferCritical: true,
    },
    {
      id: "observe-overlook",
      title: "Observation",
      sections: ["science"],
      prerequisites: [],
      region: "tinker-bluffs",
      landmark: "Gear Overlook",
      transferCritical: false,
    },
    {
      id: "measure-mesa",
      title: "Measurement",
      sections: ["science", "math"],
      prerequisites: ["observe-overlook", "add-atoll"],
      region: "tinker-bluffs",
      landmark: "Gadget Workshop",
      transferCritical: true,
    },
    {
      id: "phoneme-falls",
      title: "Phonemes",
      sections: ["reading"],
      prerequisites: [],
      region: "story-vale",
      landmark: "Whispering Falls",
      transferCritical: false,
    },
    {
      id: "blend-bay",
      title: "Blending",
      sections: ["reading"],
      prerequisites: ["phoneme-falls"],
      region: "story-vale",
      landmark: "Book-Root Forest",
      transferCritical: false,
    },
    {
      id: "letter-landing",
      title: "Letters",
      sections: ["language"],
      prerequisites: [],
      region: "wordwind-reach",
      landmark: "Letter Landing Field",
      transferCritical: false,
    },
    {
      id: "sentence-summit",
      title: "Sentences",
      sections: ["language", "reading"],
      prerequisites: ["letter-landing", "blend-bay"],
      region: "wordwind-reach",
      landmark: "The Spelling Spires",
      transferCritical: true,
    },
  ],
  edges: [
    { from: "count-cove", to: "add-atoll" },
    { from: "add-atoll", to: "place-value-point" },
    { from: "observe-overlook", to: "measure-mesa" },
    { from: "add-atoll", to: "measure-mesa" },
    { from: "phoneme-falls", to: "blend-bay" },
    { from: "letter-landing", to: "sentence-summit" },
    { from: "blend-bay", to: "sentence-summit" },
  ],
  regions: ["numbers-coast", "tinker-bluffs", "story-vale", "wordwind-reach"],
} satisfies QuestWorld;
